app/xss/urls.py
from django.urls import path

from . import views


app_name = 'xss'
urlpatterns = [
    path('project/', views.ProjectList.as_view(), name='project-create'),
    path('project/<int:pk>/', views.ProjectList.as_view(), name='project-detail'),
    path('project/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project-delete'),
    path('victim/', views.VictimList.as_view(), name='victim-list'),
    path('victim/<int:pk>/', views.VictimDetail.as_view(), name='victim-detail'),
    path('victim/<int:pk>/delete/', views.VictimDelete.as_view(), name='victim-delete'),
]

conote/urls.py
from django.urls import path, include
from django.contrib import admin

from app.rat import consumers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.log.urls', namespace='log')),

    path('auth/', include('app.ucenter.urls', namespace='auth')),
    path('xss/', include('app.xss.urls', namespace='xss')),
    path('sandbox/', include('app.sandbox.urls', namespace='sandbox')),
    path('api/', include('app.api.urls', namespace='api')),
    path('disposable_email/', include('app.disposable_email.urls', namespace='email')),
    path('rat/', include('app.rat.urls', namespace='rat'))
]

websocket_urlpatterns = [
    path('ws/rat/<str:serid>/', consumers.RatConsumer.as_asgi()),
]

app/xss/models.py
import json
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import date
from django.db.models import JSONField
from django.conf import settings
from hashids import Hashids
from django.http.cookie import parse_cookie


hashids = Hashids(salt='c0n0tE_1s_G00d_p1Atf0rM', min_length=4)


class Payload(models.Model):
    name = models.CharField('名称', max_length=128, null=True, blank=False)
    description = models.CharField('描述', max_length=256, null=True, blank=True)
    data = models.TextField('Payload')

    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modify_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_time']
        verbose_name = 'XSS攻击向量'
        verbose_name_plural = verbose_name


def generate_project_name():
    return date(timezone.localtime(timezone.now()), '项目（YmdHis）')


class Project(models.Model):
    name = models.CharField('名称', max_length=128, default=generate_project_name)
    payload = models.TextField('代码', blank=True)
    description = models.CharField('描述', max_length=256, null=True, blank=True, help_text='一些辅助性描述')

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='用户',
        on_delete=models.CASCADE,
        related_name='xss_projects'
    )

    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modify_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created_time']
        verbose_name = '项目'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return 'http://{host}/{id}'.format(host=settings.O_XSS_DOMAIN, id=hashids.encode(self.pk))

    @staticmethod
    def decode_id(ids):
        return hashids.decode(ids)

    def get_tz_url(self):
        return '//{host}/{id}.png'.format(host=settings.O_XSS_DOMAIN, id=hashids.encode(self.pk))


def return_object():
    return {}


class Victim(models.Model):
    url = models.TextField('当前URL')
    log = models.OneToOneField(
        'log.WebLog',
        verbose_name='Web日志',
        null=True,
        on_delete=models.SET_NULL
    )
    data = JSONField('数据', default=return_object)
    ip_addr = models.GenericIPAddressField('IP地址')
    location = models.CharField('地区', max_length=256, blank=True, null=True)

    project = models.ForeignKey(
        'Project',
        verbose_name='主机',
        on_delete=models.CASCADE,
        related_name='victims'
    )
    is_view = models.BooleanField('查看', default=False)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modify_time = models.DateTimeField('修改时间', auto_now=True)

    def __str__(self):
        return self.url

    class Meta:
        ordering = ['-created_time']
        verbose_name = '主机'
        verbose_name_plural = verbose_name

    def cookies(self):
        try:
            return parse_cookie(self.data.get('cookie', ''))
        except:
            return {}

    def local_storage(self):
        try:
            return json.loads(self.data.get('ls', '{}'))
        except:
            return {}

    def session_storage(self):
        try:
            return json.loads(self.data.get('ss', '{}'))
        except:
            return {}

app/xss/forms.py
from django import forms
from django.core import exceptions

from . import models
from conote.field import AceEditorTextarea


class ProjectForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = [
            'name',
            'description',
            'payload'
        ]
        widgets = {
            'payload': AceEditorTextarea()
        }

app/xss/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views import generic
from django.views.generic.edit import FormMixin

from pure_pagination.mixins import PaginationMixin
from conote.mixin import ReturnBackMixin, LogUrlMixin
from . import models, forms
from conote.const import VICTIM_SORT


User = get_user_model()


class ProjectList(AccessMixin, LogUrlMixin, ReturnBackMixin, FormMixin, generic.ListView):
    template_name = 'xss/project/list.html'
    form_class = forms.ProjectForm

    def get_queryset(self):
        return self.request.user.xss_projects.prefetch_related('victims').all()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()

        pk = self.kwargs.get('pk', None)
        try:
            self.object = request.user.xss_projects.get(pk=pk)
        except models.Project.DoesNotExist as e:
            pass

        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = super().get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'instance': self.object})
        return kwargs

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        kwargs['template_payload'] = models.Payload.objects.all().order_by('created_time')
        return super().get_context_data(**kwargs)


class ProjectDelete(LoginRequiredMixin, ReturnBackMixin, generic.DeleteView):
    get = generic.DeleteView.http_method_not_allowed

    def get_queryset(self):
        return self.request.user.xss_projects.all()


class VictimList(LoginRequiredMixin, LogUrlMixin, PaginationMixin, generic.ListView):
    template_name = 'xss/victim/list.html'
    paginate_by = 15

    def get(self, request, *args, **kwargs):
        if 'last_view_ids' in self.request.session and isinstance(self.request.session['last_view_ids'], list):
            models.Victim.objects.filter(
                project__user=self.request.user,
                id__in=self.request.session['last_view_ids']
            ).update(is_view=True)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return models.Victim.objects.filter(project__user=self.request.user).select_related('project', 'log').all()

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        self.request.session['last_view_ids'] = list(kwargs['object_list'].values_list('id', flat=True))
        return kwargs


class VictimDetail(LoginRequiredMixin, ReturnBackMixin, generic.DetailView):
    template_name = 'xss/victim/detail.html'

    def get_queryset(self):
        return models.Victim.objects.filter(project__user=self.request.user).select_related('project', 'log').all()

    def get_context_data(self, **kwargs):
        kwargs['victim_sort'] = dict(VICTIM_SORT)
        return super().get_context_data(**kwargs)


class VictimDelete(LoginRequiredMixin, ReturnBackMixin, generic.DeleteView):
    get = generic.DeleteView.http_method_not_allowed

    def get_queryset(self):
        return models.Victim.objects.filter(project__user=self.request.user).all()

templates/xss/project/list.html
{% extends 'framework.html' %}
{% load bootstrap3 %}
{% load static %}

{% block subject %}XSS收信<small>项目列表</small>{% endblock %}

{% block content %}
<div class="table-grid table-grid-desktop">
   <div class="col col-xxl">
      <div class="pr">
         <div class="clearfix mb">
            <button class="btn btn-sm btn-default mb-toggle-button pull-right dropdown-toggle" type="button" data-toggle="collapse" data-target=".mb-boxes">
               <em class="fa fa-bars fa-fw fa-lg"></em>
            </button>
            <a class="btn btn-purple btn-sm mb-compose-button" href="{% url 'xss:project-create' %}">
               <em class="fa fa-pencil"></em>
               <span>创建项目</span>
            </a>
         </div>
         <!-- START mailbox list-->
         <div class="mb-boxes collapse">
            <div class="panel panel-default">
               <div class="panel-body">
                  <ul class="nav nav-pills nav-stacked">
                     <li class="p">
                        <small class="text-muted">项目列表</small>
                     </li>
                     {% for object in object_list %}
                     <li class="{% if form.instance and form.instance.pk == object.pk %}active{% endif %}">
                        <a href="{% url 'xss:project-detail' pk=object.pk %}">
                           <span class="label label-green pull-right">{{ object.victims.count }}</span>
                           <em class="fa fa-fw fa-lg fa-inbox"></em>
                           <span>{{ object.name }}</span>
                        </a>
                     </li>
                     {% endfor %}
                  </ul>
               </div>
            </div>
         </div>
         <!-- END mailbox list-->
      </div>
   </div>
   <div class="col">
      <!-- START action buttons-->
      <div class="clearfix mb">
         <div class="btn-group pull-left">
            <button class="btn btn-default btn-sm" type="button">
               <em class="fa fa-mail-reply text-gray-dark"></em>
            </button>
            <button class="btn btn-default btn-sm" type="button">
               <em class="fa fa-mail-reply-all text-gray-dark"></em>
            </button>
            <button class="btn btn-default btn-sm" type="button">
               <em class="fa fa-mail-forward text-gray-dark"></em>
            </button>
         </div>
         <div class="btn-group pull-right">
            {% if form.instance.pk %}
            <button class="btn btn-danger btn-sm" type="button" onclick="post_submit('{% url 'xss:project-delete' pk=form.instance.pk %}')">删除</button>
            {% endif %}
            <button class="btn-sm btn btn-purple" type="button" id="project-submit">提交</button>
         </div>
      </div>
      <div class="panel panel-default">
         <div class="panel-body">
             <form method="post" enctype="multipart/form-data" id="project-form">
                 {% bootstrap_form form %}
                 {% csrf_token %}
             </form>
         </div>
      </div>
   </div>
</div>
<div id="btn-panel" class="btn-panel">
    <button class="btn btn-default btn-sm" type="button" id="minify">压缩</button>
    <button class="btn btn-default btn-sm" type="button" id="beautify">美化</button>

    {% if form.instance.pk %}
    <button class="btn btn-default btn-sm clip-btn" type="button" data-clipboard-text="{{ form.instance.get_absolute_url }}">复制JS地址</button>
    {% endif %}

    <div class="pull-right" style="width: 30%">
        <select id="payload-template" class="chosen-select input-md form-control pull-right"
                data-placeholder="插入Payload模板...">
        <option value=""></option>
        <optgroup label="插入一个预置XSS模块...">
         {% for payload in template_payload %}
           <option value="{{ payload.data }}">{{ payload }}</option>
         {% endfor %}
        </optgroup>
      </select>
    </div>
</div>
{% endblock %}

{% block addstyle %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.13.1/min/vs/editor/editor.main.css" integrity="sha256-LsEYYWoTcOfDc0LahYNMoYGUAMKPg6v8u7HvULUfdwE=" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'vendor/chosen/chosen.min.css' %}">
<style type="text/css">
.btn-panel { margin-bottom: 10px; display: none; }
#editor {
    border: 1px solid lightgray;
    margin: auto;
    height: 400px;
    width: 100%;
}
.pager {
    margin: 0;
}
</style>
{% endblock %}

{% block addscript %}
<script src="{% static 'vendor/chosen/chosen.jquery.min.js' %}"></script>
<script src="{% static 'js/xss/bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/monaco-editor@0.13.1/min/vs/loader.js" integrity="sha256-BRLZ7T5bs9rvlKpcFqbD4u4m/+2d4A0UNP/kagJ7Frk=" crossorigin="anonymous"></script>
<script src="{% static 'js/xss/xss.min.js' %}"></script>
{% endblock %}