app/log/urls.py
from django.urls import path, re_path

from . import views


app_name = 'log'
urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
    path('refresh/api/', views.RefreshApiKey.as_view(), name='refresh-apikey'),

    path('weblog/list/', views.WebLogList.as_view(), name='weblog-list'),
    path('weblog/<int:pk>/', views.WebLogDetail.as_view(), name='weblog-detail'),
    path('weblog/<int:pk>/delete/', views.WebLogDelete.as_view(), name='weblog-delete'),

    path('dnslog/list/', views.DNSLogList.as_view(), name='dnslog-list'),
    path('delete/', views.LogDelete.as_view(), name='log-delete'),

    path('note/list/', views.NoteList.as_view(), name='note-list'),
    re_path('^note/create/(?P<action>text|file|code|article)/$', views.NoteCreate.as_view(), name='note-create'),

    path('note/<int:pk>/delete/', views.NoteDelete.as_view(), name='note-delete'),
    path('note/<int:pk>/update/', views.NoteUpdate.as_view(), name='note-update'),
    path('note/<int:pk>/preview/', views.NotePreview.as_view(), name='note-preview'),

    path('shortdomain/list/', views.ShortDomainList.as_view(), name='shortdomain-list'),
    path('shortdomain/create/', views.ShortDomainCreate.as_view(), name='shortdomain-create'),
    path('shortdomain/<int:pk>/update/', views.ShortDomainUpdate.as_view(), name='shortdomain-update'),
    path('shortdomain/<int:pk>/delete/', views.ShortDomainDelete.as_view(), name='shortdomain-delete'),

    path('dns_record/', views.DNSRecordUpdate.as_view(), name='dns-record'),
]

conote/urls.py
from django.urls import path, include
from django.contrib import admin

from app.rat import consumers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.log.urls', namespace='log')),

    path('auth/', include('app.ucenter.urls', namespace='auth')),
    path('xss/', include('app.xss.urls', namespace='xss')),
    path('sandbox/', include('app.sandbox.urls', namespace='sandbox')),
    path('api/', include('app.api.urls', namespace='api')),
    path('disposable_email/', include('app.disposable_email.urls', namespace='email')),
    path('rat/', include('app.rat.urls', namespace='rat'))
]

websocket_urlpatterns = [
    path('ws/rat/<str:serid>/', consumers.RatConsumer.as_asgi()),
]

templates/shortdomain/form.html
{% extends 'form.html' %}

{% block subject %}短域名{% endblock %}

{% block form_title %}我的短域名{% endblock %}

templates/shortdomain/list.html
{% extends 'framework.html' %}

{% block subject %}短域名{% endblock %}

{% block content %}
<div class="panel panel-default">
 <div class="panel-heading">操作</div>
 <div class="panel-body">
    <a type="button" class="btn btn-labeled btn-info" href="{% url 'log:shortdomain-create' %}">
       <span class="btn-label"><i class="icon-plus"></i>
       </span>增加短域名</a>
 </div>
</div>

<div class="panel panel-default">
 <div class="panel-heading">我的短域名</div>
 <div class="panel-body">
    <div class="table-responsive">
       <table class="table table-striped">
          <thead>
             <tr>
                <th>时间</th>
                <th>域名</th>
                <th class="table-path">目标地址</th>
                <th>点击量</th>
                <th>管理</th>
             </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
             <tr>
                <td>{{ object.created_time | date:"Y-m-d H:i:s" }}</td>
                <td><a href="{{ object.get_absolute_url }}" target="_blank">{{ object.get_absolute_url }}</a></td>
                <td class="table-path">{{ object.target }}</td>
                <td>{{ object.click }}</td>
                <td>
                    <a type="button" class="mb-sm btn-xs btn btn-primary btn-outline"
                       href="{% url 'log:shortdomain-update' pk=object.pk %}">编辑</a>
                    <button type="button" class="mb-sm btn-xs btn btn-danger btn-outline confirm"
                            onclick="post_submit('{% url 'log:shortdomain-delete' pk=object.pk %}')">删除</button>
                </td>
             </tr>
            {% endfor %}
          </tbody>
       </table>
    </div>
 </div>
 {% if is_paginated %}
 <div class="panel-footer">
   <div class="pull-right">
    {% include 'pure_pagination/pagination-bootstrap.html' %}
   </div>
   <div class="clearfix"></div>
</div>
 {% endif %}
</div>
{% endblock %}