app/log/urls.py
from django.urls import path, re_path

from . import views


app_name = 'log'
urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
    path('refresh/api/', views.RefreshApiKey.as_view(), name='refresh-apikey'),

    path('weblog/list/', views.WebLogList.as_view(), name='weblog-list'),
    path('weblog/<int:pk>/', views.WebLogDetail.as_view(), name='weblog-detail'),
    path('weblog/<int:pk>/delete/', views.WebLogDelete.as_view(), name='weblog-delete'),

    path('dnslog/list/', views.DNSLogList.as_view(), name='dnslog-list'),
    path('delete/', views.LogDelete.as_view(), name='log-delete'),

    path('note/list/', views.NoteList.as_view(), name='note-list'),
    re_path('^note/create/(?P<action>text|file|code|article)/$', views.NoteCreate.as_view(), name='note-create'),

    path('note/<int:pk>/delete/', views.NoteDelete.as_view(), name='note-delete'),
    path('note/<int:pk>/update/', views.NoteUpdate.as_view(), name='note-update'),
    path('note/<int:pk>/preview/', views.NotePreview.as_view(), name='note-preview'),

    path('shortdomain/list/', views.ShortDomainList.as_view(), name='shortdomain-list'),
    path('shortdomain/create/', views.ShortDomainCreate.as_view(), name='shortdomain-create'),
    path('shortdomain/<int:pk>/update/', views.ShortDomainUpdate.as_view(), name='shortdomain-update'),
    path('shortdomain/<int:pk>/delete/', views.ShortDomainDelete.as_view(), name='shortdomain-delete'),

    path('dns_record/', views.DNSRecordUpdate.as_view(), name='dns-record'),
]

app/ucenter/urls.py
from django.urls import path

from . import views


app_name = 'ucenter'
urlpatterns = [
    path('login/', views.jump_for_login, name='login'),
    path('callback/', views.callback, name='callback'),
    path('check/', views.RegisterView.as_view(), name='check'),

    path('option/', views.OptionView.as_view(), name='option')
]

conote/urls.py
from django.urls import path, include
from django.contrib import admin

from app.rat import consumers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.log.urls', namespace='log')),

    path('auth/', include('app.ucenter.urls', namespace='auth')),
    path('xss/', include('app.xss.urls', namespace='xss')),
    path('sandbox/', include('app.sandbox.urls', namespace='sandbox')),
    path('api/', include('app.api.urls', namespace='api')),
    path('disposable_email/', include('app.disposable_email.urls', namespace='email')),
    path('rat/', include('app.rat.urls', namespace='rat'))
]

websocket_urlpatterns = [
    path('ws/rat/<str:serid>/', consumers.RatConsumer.as_asgi()),
]

templates/index/list.html
{% extends 'framework.html' %}

{% block subject %}主页{% endblock %}

{% block content %}
<div class="panel panel-default">
 <div class="panel-heading">基本信息</div>
 <div class="panel-body">
   <table class="table table-striped">
          <thead>
             <tr>
                <th>域名</th>
                <th>API Key</th>
                <th>API文档</th>
             </tr>
          </thead>
          <tbody>
            <tr>
                <td>
                    <code>{{ request.user.get_user_domain }}</code>
                </td>
                <td>{{ request.user.apikey }}</td>
                <td>尚无API</td>
            </tr>

          </tbody>
   </table>
 </div>
 <div class="panel-footer">
    <button class="btn btn-info btn-xs btn-outline btn-square btn-copy" type="button" data-clipboard-text="{{ request.user.get_user_domain }}">复制域名</button>
    <a class="btn btn-info btn-xs btn-outline btn-square" href="{% url 'auth:option' %}">全局设置</a>
    <button type="button" class="btn btn-warning btn-xs btn-square" onclick="return post_submit('{% url 'log:refresh-apikey' %}')">刷新API Key</button>
    <button type="button" class="btn btn-danger btn-xs btn-square" onclick="return post_submit('{% url 'log:log-delete' %}', {query:'dns'})">清空DNS记录</button>
    <button type="button" class="btn btn-danger btn-xs btn-square" onclick="return post_submit('{% url 'log:log-delete' %}', {query:'web'})">清空Web记录</button>
    <button type="button" class="btn btn-danger btn-xs btn-square" onclick="return post_submit('{% url 'log:log-delete' %}', {query:'all'})">清空所有记录</button>
 </div>
</div>
<div class="panel panel-default">
 <div class="panel-heading">Web日志</div>
 <div class="panel-body">
       <table class="table table-striped">
          <thead>
             <tr>
                <th>时间</th>
                <th>方法</th>
                <th>Host</th>
                <th class="hidden-xs hidden-sm table-path">Path</th>
                <th>IP地址</th>
                <th>管理</th>
             </tr>
          </thead>
          <tbody>
            {% for object in weblog_list %}
             <tr>
                <td>{{ object.created_time | date:"Y-m-d H:i:s" }}</td>
                <td>{{ object.method }}</td>
                <td>{{ object.hostname }}</td>
                <td class="hidden-xs hidden-sm table-path">{{ object.path }}</td>
                <td><span class="label label-info">{{ object.ip_addr }}</span></td>
                <td>
                    <a class="btn-xs btn btn-primary btn-outline"
                       href="{% url 'log:weblog-detail' pk=object.pk %}">查看</a>
                    <a class="btn-xs btn btn-danger btn-outline"
                       href="javascript:post_submit('{% url 'log:weblog-delete' pk=object.pk %}')">刪除</a>
                </td>
             </tr>
            {% endfor %}
          </tbody>
       </table>
 </div>
</div>

<div class="panel panel-default">
 <div class="panel-heading">DNS日志</div>
 <div class="panel-body">
    <div class="table-responsive">
       <table class="table table-striped">
          <thead>
             <tr>
                <th width="10%">时间</th>
                <th>域名</th>
                <th width="10%">类型</th>
                <th width="15%">管理</th>
             </tr>
          </thead>
          <tbody>
            {% for object in dnslog_list %}
             <tr>
                <td>{{ object.created_time | date:"Y-m-d H:i:s" }}</td>
                <td>{{ object.hostname }}</td>
                <td>{{ object.dns_type }}</td>
                <td>
                    <a type="button" class="btn-xs btn btn-primary btn-outline">查看</a>
                </td>
             </tr>
            {% endfor %}
          </tbody>
       </table>
    </div>
 </div>
</div>
{% endblock %}

{% block addscript %}
<script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.1/dist/clipboard.min.js" integrity="sha256-hIvIxeqhGZF+VVeM55k0mJvWpQ6gTkWk3Emc+NmowYA=" crossorigin="anonymous"></script>
<script>
(function(window, document, $, undefined){
  $(function(){
      new ClipboardJS('.btn-copy');
  });
})(window, document, window.jQuery);
</script>
{% endblock %}