app/disposable_email/urls.py
from django.urls import path, re_path

from . import views


app_name = 'disposable_email'
urlpatterns = [
    path('', views.EmailList.as_view(), name='list'),
    path('<int:pk>/', views.EmailDetail.as_view(), name='detail'),
    path('<int:pk>/download/', views.EmailDownload.as_view(), name='download'),
    path('<int:pk>/delete/', views.EmailDelete.as_view(), name='delete'),
    path('flush/', views.EmailFlush.as_view(), name='flush'),
    path('<int:pk>/box/delete/', views.BoxDelete.as_view(), name='box-delete'),
    path('generate/', views.EmailGenerate.as_view(), name='generate'),
]

app/log/urls.py
from django.urls import path, re_path

from . import views


app_name = 'log'
urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
    path('refresh/api/', views.RefreshApiKey.as_view(), name='refresh-apikey'),

    path('weblog/list/', views.WebLogList.as_view(), name='weblog-list'),
    path('weblog/<int:pk>/', views.WebLogDetail.as_view(), name='weblog-detail'),
    path('weblog/<int:pk>/delete/', views.WebLogDelete.as_view(), name='weblog-delete'),

    path('dnslog/list/', views.DNSLogList.as_view(), name='dnslog-list'),
    path('delete/', views.LogDelete.as_view(), name='log-delete'),

    path('note/list/', views.NoteList.as_view(), name='note-list'),
    re_path('^note/create/(?P<action>text|file|code|article)/$', views.NoteCreate.as_view(), name='note-create'),

    path('note/<int:pk>/delete/', views.NoteDelete.as_view(), name='note-delete'),
    path('note/<int:pk>/update/', views.NoteUpdate.as_view(), name='note-update'),
    path('note/<int:pk>/preview/', views.NotePreview.as_view(), name='note-preview'),

    path('shortdomain/list/', views.ShortDomainList.as_view(), name='shortdomain-list'),
    path('shortdomain/create/', views.ShortDomainCreate.as_view(), name='shortdomain-create'),
    path('shortdomain/<int:pk>/update/', views.ShortDomainUpdate.as_view(), name='shortdomain-update'),
    path('shortdomain/<int:pk>/delete/', views.ShortDomainDelete.as_view(), name='shortdomain-delete'),

    path('dns_record/', views.DNSRecordUpdate.as_view(), name='dns-record'),
]

app/rat/urls.py
from django.urls import path, re_path

from . import views


app_name = 'rat'
urlpatterns = [
    path('list/', views.ClientList.as_view(), name='rat-list'),
    path('detail/<str:pk>/', views.ClientManager.as_view(), name='rat-detail'),
    path('execute/', views.CommandExecute.as_view(), name='rat-execute'),
]

app/xss/urls.py
from django.urls import path

from . import views


app_name = 'xss'
urlpatterns = [
    path('project/', views.ProjectList.as_view(), name='project-create'),
    path('project/<int:pk>/', views.ProjectList.as_view(), name='project-detail'),
    path('project/<int:pk>/delete/', views.ProjectDelete.as_view(), name='project-delete'),
    path('victim/', views.VictimList.as_view(), name='victim-list'),
    path('victim/<int:pk>/', views.VictimDetail.as_view(), name='victim-detail'),
    path('victim/<int:pk>/delete/', views.VictimDelete.as_view(), name='victim-delete'),
]

conote/urls.py
from django.urls import path, include
from django.contrib import admin

from app.rat import consumers

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.log.urls', namespace='log')),

    path('auth/', include('app.ucenter.urls', namespace='auth')),
    path('xss/', include('app.xss.urls', namespace='xss')),
    path('sandbox/', include('app.sandbox.urls', namespace='sandbox')),
    path('api/', include('app.api.urls', namespace='api')),
    path('disposable_email/', include('app.disposable_email.urls', namespace='email')),
    path('rat/', include('app.rat.urls', namespace='rat'))
]

websocket_urlpatterns = [
    path('ws/rat/<str:serid>/', consumers.RatConsumer.as_asgi()),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Bootstrap Admin App + jQuery">
   <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
   <title>{% block title %}CoNote{% endblock %}</title>
   <!-- =============== VENDOR STYLES ===============-->
   <!-- FONT AWESOME-->
   <link rel="stylesheet" href="{% static 'vendor/fontawesome/css/font-awesome.min.css' %}">
   <!-- SIMPLE LINE ICONS-->
   <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}">
   <!-- ANIMATE.CSS-->
   <link rel="stylesheet" href="{% static 'vendor/animate.css/animate.min.css' %}">
   <link rel="stylesheet" href="{% static 'vendor/sweetalert/dist/sweetalert.css' %}">
   <!-- =============== PAGE VENDOR STYLES ===============-->
   <!-- =============== BOOTSTRAP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" id="bscss">
   <!-- =============== APP STYLES ===============-->
   <link rel="stylesheet" href="{% static 'css/app.css' %}" id="maincss">
    <meta name="csrfmiddlewaretoken" content="{{ csrf_token }}">
   {% block addstyle %}{% endblock %}
</head>

<body class="aside-float">
   {% block body %}{% endblock %}
   <!-- =============== VENDOR SCRIPTS ===============-->
   <!-- MODERNIZR-->
   <script src="{% static 'vendor/modernizr/modernizr.custom.js' %}"></script>
   <!-- JQUERY-->
   <script src="{% static 'vendor/jquery/dist/jquery.js' %}"></script>
   <!-- BOOTSTRAP-->
   <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.js' %}"></script>
   <!-- STORAGE API-->
   <script src="{% static 'vendor/jQuery-Storage-API/jquery.storageapi.js' %}"></script>
   <!-- JQUERY EASING-->
   <script src="{% static 'vendor/jquery.easing/js/jquery.easing.js' %}"></script>
   <!-- ANIMO-->
   <script src="{% static 'vendor/animo.js/animo.js' %}"></script>
   <!-- =============== PAGE VENDOR SCRIPTS ===============-->
   <script src="{% static 'vendor/sweetalert/dist/sweetalert.min.js' %}"></script>
   {% block addscript %}{% endblock %}

   <!-- =============== APP SCRIPTS ===============-->
   <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

templates/form.html
{% extends 'framework.html' %}
{% load bootstrap3 %}
{% load static %}

{% block subject %}{% endblock %}

{% block content %}
<div class="panel panel-default">
 <div class="panel-heading">{% block form_title %}{% endblock %}</div>
 <div class="panel-body">
    <form role="form" method="post" enctype="multipart/form-data">
       {% bootstrap_form form %}

       <a type="button" class="mb-sm btn btn-default" href="{{ request.session.back_url }}">返回</a>
       <button type="submit" class="mb-sm btn btn-success">提交</button>

       {% csrf_token %}
    </form>

 </div>
</div>
{% endblock %}

templates/framework.html
{% extends 'main.html' %}

{% block main %}
<div class="content-wrapper">
  <div class="content-heading">
     {% block subject %}Title{% endblock %}
  </div>
  {% block content %}{% endblock %}
</div>
{% endblock %}

templates/main.html
{% extends 'base.html' %}

{% block body %}
<div class="wrapper">
      <!-- top navbar-->
      <header class="topnavbar-wrapper">
         <!-- START Top Navbar-->
         <nav role="navigation" class="navbar topnavbar">
            <!-- START navbar header-->
            <div class="navbar-header">
               <a href="{% url 'log:index' %}" class="navbar-brand">
                  <div class="brand-logo">

                  </div>
               </a>
            </div>
            <!-- END navbar header-->
            <!-- START Nav wrapper-->
            <div class="nav-wrapper">
               <!-- START Left navbar-->
               <ul class="nav navbar-nav">
                  <li>
                     <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                     <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
                        <em class="fa fa-navicon"></em>
                     </a>
                     <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                     <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                        <em class="fa fa-navicon"></em>
                     </a>
                  </li>
               </ul>
               <!-- END Left navbar-->
            </div>
            <!-- END Nav wrapper-->
         </nav>
         <!-- END Top Navbar-->
      </header>
      <!-- sidebar-->
      <aside class="aside">
         <!-- START Sidebar (left)-->
         <div class="aside-inner">

            {% if request.resolver_match.view_name in 'log:note-list,log:weblog-list,log:dnslog-list,sandbox:sandbox-list' %}
         
            <div id="search-box">
               <input id="main-search-input" class="form-control" type="text" placeholder="Search" name="query">
            </div>

            {% endif %}

            <nav data-sidebar-anyclick-close="" class="sidebar">
               <!-- START sidebar nav-->
               <ul class="nav">
                  <li>
                     <a href="{% url 'log:index' %}" title="Single View">
                        <em class="fa fa-dashboard"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">主页</span>
                     </a>
                  </li>
                  <li class=" ">
                     <a href="#menu-log" title="Menu" data-toggle="collapse">
                        <em class="icon-list"></em>
                        <span data-localize="sidebar.nav.menu.MENU">日志</span>
                     </a>
                     <ul id="menu-log" class="nav sidebar-subnav collapse in">
                        <li class="sidebar-subnav-header">log</li>
                        <li class=" ">
                           <a href="{% url 'log:weblog-list' %}" title="Sub Menu">
                              <span data-localize="sidebar.nav.menu.SUBMENU">Web日志</span>
                           </a>
                        </li>
                        <li class=" ">
                           <a href="{% url 'log:dnslog-list' %}" title="Sub Menu">
                              <span data-localize="sidebar.nav.menu.SUBMENU">DNS日志</span>
                           </a>
                        </li>
                     </ul>
                  </li>
                  <li>
                     <a href="{% url 'log:note-list' %}" title="Single View">
                        <em class="icon-pencil"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">文件服务</span>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'log:shortdomain-list' %}" title="Single View">
                        <em class="icon-link"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">短域名</span>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'log:dns-record' %}" title="Single View">
                        <em class="icon-envelope"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">DNS服务器</span>
                     </a>
                  </li>
                  <li>
                      <a href="#menu-xss" title="Menu" data-toggle="collapse">
                        <em class="icon-ghost"></em>
                        <span data-localize="sidebar.nav.menu.MENU">XSS收信</span>
                     </a>
                     <ul id="menu-xss" class="nav sidebar-subnav collapse in">
                        <li class="sidebar-subnav-header">XSS收信</li>
                        <li class=" ">
                           <a href="{% url 'xss:project-create' %}" title="Project List">
                              <span data-localize="sidebar.nav.menu.SUBMENU">项目列表</span>
                           </a>
                        </li>
                        <li class=" ">
                           <a href="{% url 'xss:victim-list' %}" title="Victim List">
                              <span data-localize="sidebar.nav.menu.SUBMENU">结果列表</span>
                           </a>
                        </li>
                     </ul>
                  </li>
                  <li>
                     <a href="{% url 'sandbox:sandbox-list' %}" title="Single View">
                        <em class="icon-layers"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">我的沙盒</span>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'disposable_email:list' %}" title="Single View">
                        <em class="fa fa-inbox"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">域名邮箱</span>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'rat:rat-list' %}" title="Single View">
                        <em class="icon-key"></em>
                        <span data-localize="sidebar.nav.SINGLEVIEW">远程终端</span>
                     </a>
                  </li>
               </ul>
               <!-- END sidebar nav-->
            </nav>
         </div>
         <!-- END Sidebar (left)-->
      </aside>
      <!-- offsidebar-->
      <section>
         <!-- Page content-->
         {% block main %}{% endblock %}
      </section>
      <!-- Page footer-->
      <footer>
         <span>&copy; {% now 'Y' %} - Conote</span>
      </footer>
   </div>
{% endblock %}